// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFeedbackComponent: typeof import('./components/AppFeedbackComponent.vue')['default']
    AppRatingComponent: typeof import('./components/AppRatingComponent.vue')['default']
    AppRatingStarComponent: typeof import('./components/AppRatingStarComponent.vue')['default']
    BookComponent: typeof import('./components/BookComponent.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LoaderComponent: typeof import('./components/LoaderComponent.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
